// Name: Aman Gupta
// ID: 2014B2A70201P

#include <string.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include "lexer.h"
#include "parser.h"

int main(int argc, char* argv[])
// int main()
{
    printf("(a) FIRST and FOLLOW set HARDCODED\n(b) Both lexical and syntax analysis modules implemented\n(c) Lexer & Parser both work correctly for all 5 testcases\n(d) Error recovery implemented for Lexer\n(e) Modules compile and execute without Segmentation Fault on all given testcases.\n\n");
    FILE* fp = fopen(argv[1],"r");
    if(fp==NULL)
    {
        printf("FILE NOT FOUND. TERMINATING!!\n");
        exit(0);
    }
    FILE* fp2;
    // FILE* fp = fopen("temp.txt","r");
    int opt;
    // int opt = 2;
    printf("Select one of the options mentioned below:\n");
    printf("1: For removal of comments ‐ print the comment free code on the console\n");
    printf("2: For printing the token list (on the console) generated by the lexer.\n");
    printf("3: For parsing to verify the syntactic correctness of the input source code\n");
    printf("4: For printing the parse tree appropriately\n");
    // scanf("Enter your choice: %d",&opt);
    printf("\nEnter Your Choice: ");
    scanf("%d",&opt);
    if(opt==1)
        removeComments(fp);
    else if(opt==2)
    {
        // tokenInfo* newToken;
        tokenInfo* newToken = (tokenInfo*)malloc(sizeof(tokenInfo));
        while(true)
        {
            // newToken = createToken();
            strcpy(newToken->lexeme,"");
            newToken->tokenID = ERR;
            getNextToken(fp,newToken);
            // printf("%s\n", enumToString(newToken->tokenID));
            if(newToken->tokenID==DOLLAR)
                exit(0);
            else if(newToken->tokenID!=ERR)
                printToken(newToken);
        }
    }
    else if(opt==3)
    {
        FILE* fp2 = fopen(argv[2],"w");
        createParseTree(fp,fp2);
        fclose(fp2);
    }
    else if(opt==4)
    {
        FILE* fp2 = fopen(argv[2],"r");
        printParseTree(fp2);
        fclose(fp2);
    }
    else
        printf("Wrong Option Entered. TERMINATING!!\n");
    fclose(fp);
    return 0;
}